version: '3.4'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring:
  coalbase_backend:
    external: true

services:
  prometheus:
    image: docker.nexus.archi-lab.io/archilab/prometheus-custom:${BUILD_ID}
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - cadvisor
    networks:
      - coalbase_backend
      - monitoring
    deploy:
      restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
      placement:
        constraints:
          - node.role==manager
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - coalbase_backend
    deploy:
      restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
      mode: global
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - coalbase_backend
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: global
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  grafana:
    image: docker.nexus.archi-lab.io/archilab/grafana-custom:${BUILD_ID}
    deploy:
      restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
